import { ApiProperty } from '@nestjs/swagger';

export class VerifySiweDto {
  @ApiProperty({
    description: 'EVM address to check against.',
    type: String,
    example: '0xf39fd6e51aad88f6f4ce6ab8827279cfffb92266',
  })
  address: string;

  @ApiProperty({
    description:
      "The signature that was generated by signing the message with the address's signer.",
    type: String,
    example:
      '0x66edc32e2ab001213321ab7d959a2207fcef5190cc9abb6da5b0d2a8a9af2d4d2b0700e2c317c4106f337fd934fbbb0bf62efc8811a78603b33a8265d3b8f8cb1c',
  })
  signature: string;
}
