import createFetchClient from "openapi-fetch";
import createClient from "openapi-react-query";
import type { paths } from "../generated/api-v1"; // generated by openapi-typescript

const fetchClient = createFetchClient<paths>({ baseUrl: "/api" });
export const $api = createClient(fetchClient);
